baseURL = "https://garrettbyrd.net"
description = "Garrett Byrd. Software Engineer."
enableRobotsTXT = true
languageCode = "en-us"
theme = "diary"
title = "Garrett Byrd"
copyright = "2025 Garrett Byrd"

[outputs]
  home = ["HTML", "RSS"]

[params]
  author = "Garrett Byrd"
  enableAutoDarkMode=true
  favicon = "favicon.png"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Acknowledgments"
    url = "/acknowledgments/"
    weight = 3

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark.renderer]
    unsafe = true